name: Lint

on:
  - push
  - pull_request

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install --global awesome-lint
      - run: awesome-lint README.md
  awesome-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: gem install awesome_bot
      # - run: awesome_bot README.md --allow 302,307 --allow-ssl --allow-dupe --white-list "linode.com"
      - run: awesome_bot README.md --allow 302 --white-list "linode.com","https://europython.eu/","https://twitter.com/PalletsTeam","https://www.reddit.com/r/flask/","https://www.udacity.com/course/full-stack-foundations--ud088","https://www.udacity.com/course/designing-restful-apis--ud388"
